// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AfvoUIClient is the client API for AfvoUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AfvoUIClient interface {
	// ListVafmSpecs returns a list of VAF Manager(s) that can be started through the UI.
	ListVafmSpecs(ctx context.Context, in *ListVafmSpecsRequest, opts ...grpc.CallOption) (AfvoUI_ListVafmSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type afvoUIClient struct {
	cc grpc.ClientConnInterface
}

func NewAfvoUIClient(cc grpc.ClientConnInterface) AfvoUIClient {
	return &afvoUIClient{cc}
}

func (c *afvoUIClient) ListVafmSpecs(ctx context.Context, in *ListVafmSpecsRequest, opts ...grpc.CallOption) (AfvoUI_ListVafmSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &AfvoUI_ServiceDesc.Streams[0], "/v1.AfvoUI/ListVafmSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &afvoUIListVafmSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AfvoUI_ListVafmSpecsClient interface {
	Recv() (*ListVafmSpecsResponse, error)
	grpc.ClientStream
}

type afvoUIListVafmSpecsClient struct {
	grpc.ClientStream
}

func (x *afvoUIListVafmSpecsClient) Recv() (*ListVafmSpecsResponse, error) {
	m := new(ListVafmSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *afvoUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.AfvoUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AfvoUIServer is the server API for AfvoUI service.
// All implementations must embed UnimplementedAfvoUIServer
// for forward compatibility
type AfvoUIServer interface {
	// ListVafmSpecs returns a list of VAF Manager(s) that can be started through the UI.
	ListVafmSpecs(*ListVafmSpecsRequest, AfvoUI_ListVafmSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedAfvoUIServer()
}

// UnimplementedAfvoUIServer must be embedded to have forward compatible implementations.
type UnimplementedAfvoUIServer struct {
}

func (UnimplementedAfvoUIServer) ListVafmSpecs(*ListVafmSpecsRequest, AfvoUI_ListVafmSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListVafmSpecs not implemented")
}
func (UnimplementedAfvoUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedAfvoUIServer) mustEmbedUnimplementedAfvoUIServer() {}

// UnsafeAfvoUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AfvoUIServer will
// result in compilation errors.
type UnsafeAfvoUIServer interface {
	mustEmbedUnimplementedAfvoUIServer()
}

func RegisterAfvoUIServer(s grpc.ServiceRegistrar, srv AfvoUIServer) {
	s.RegisterService(&AfvoUI_ServiceDesc, srv)
}

func _AfvoUI_ListVafmSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListVafmSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AfvoUIServer).ListVafmSpecs(m, &afvoUIListVafmSpecsServer{stream})
}

type AfvoUI_ListVafmSpecsServer interface {
	Send(*ListVafmSpecsResponse) error
	grpc.ServerStream
}

type afvoUIListVafmSpecsServer struct {
	grpc.ServerStream
}

func (x *afvoUIListVafmSpecsServer) Send(m *ListVafmSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AfvoUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AfvoUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.AfvoUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AfvoUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AfvoUI_ServiceDesc is the grpc.ServiceDesc for AfvoUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AfvoUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.AfvoUI",
	HandlerType: (*AfvoUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _AfvoUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListVafmSpecs",
			Handler:       _AfvoUI_ListVafmSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "afvo-ui.proto",
}
